### ISSUE TITLE
write_file_chunk doesn't check number of bytes written

### ISSUE THREAD

**Issue by bentsi** [bloomreach/s4cmd#101]
In write_file_chunk function when writing the chunk with os.write(fd, data) the actual number of bytes written is not checked. Some file systems (mostly distributed) sometimes doesn't write all the data requested and return partial write (number of bytes written less than length of data).
This can lead to data corruption.

**Comment by navinpai** [comment]
This fix was merged with master. Thanks for the suggestion and raising the issue!
