### ISSUE TITLE
Cannot dsync s3 folders to local 

### ISSUE THREAD

**Issue by dogenius01** [bloomreach/s4cmd#125]
i get error messages, when try to dsync s3 folders(empty) to local.

"[Runtime Failure] The obj "images" does not exists."
The images is a folder in s3 and not exist in local.

But, with sync not dsync operation it copies the folder.

**Comment by dogenius01** [comment]
(D)s4cmd.py:661  read S3 keys from $HOME/.s3cfg file
  (D)s4cmd.py:134  >> dsync_handler(<__main__.CommandHandler object at 0x7f5183f6f9d0>, ['dsync', 's3://kinx-log/', '/usr/local/globalcdn/s3_test/'])
  (D)s4cmd.py:134  >> validate(<__main__.CommandHandler object at 0x7f5183f6f9d0>, 'cmd|s3,local|s3,local', ['dsync', 's3://kinx-log/', '/usr/local/globalcdn/s3_test/'])
  (D)s4cmd.py:136  << validate(<__main__.CommandHandler object at 0x7f5183f6f9d0>, 'cmd|s3,local|s3,local', ['dsync', 's3://kinx-log/', '/usr/local/globalcdn/s3_test/']): None
  (D)s4cmd.py:134  >> dsync_files(<__main__.S3Handler object at 0x7f5183f6f910>, 's3://kinx-log/', '/usr/local/globalcdn/s3_test/')
  (D)s4cmd.py:134  >> relative_dir_walk(<__main__.S3Handler object at 0x7f5183f6f910>, 's3://kinx-log/')
  (D)s4cmd.py:134  >> s3walk(<__main__.S3Handler object at 0x7f5183f6f910>, 's3://kinx-log/')
  (D)s4cmd.py:134  >> s3walk(<ThreadUtil(Thread-1, started daemon 139988074669824)>, <__main__.S3URL instance at 0x7f5183859248>, '', '', [])
  (D)s4cmd.py:404  >> S3APICALL get_paginator('list_objects')
  (D)s4cmd.py:406  << S3APICALL get_paginator('list_objects'): <botocore.client.S3.Paginator.ListObjects object at 0x7f5182f038d0>
  (D)s4cmd.py:134  >> partial_match(<ThreadUtil(Thread-1, started daemon 139988074669824)>, u'emptyFolder/', '')
  (D)s4cmd.py:136  << partial_match(<ThreadUtil(Thread-1, started daemon 139988074669824)>, u'emptyFolder/', ''): True
  (D)s4cmd.py:134  >> s3walk(<ThreadUtil(Thread-2, started daemon 139988065752832)>, <__main__.S3URL instance at 0x7f5183859248>, u'emptyFolder/', '', [])
  (D)s4cmd.py:404  >> S3APICALL get_paginator('list_objects')
  (D)s4cmd.py:406  << S3APICALL get_paginator('list_objects'): <botocore.client.S3.Paginator.ListObjects object at 0x7f51826dd050>
  (D)s4cmd.py:136  << s3walk(<ThreadUtil(Thread-1, started daemon 139988074669824)>, <__main__.S3URL instance at 0x7f5183859248>, '', '', []): None
  (D)s4cmd.py:134  >> partial_match(<ThreadUtil(Thread-2, started daemon 139988065752832)>, u'emptyFolder/', '')
  (D)s4cmd.py:136  << partial_match(<ThreadUtil(Thread-2, started daemon 139988065752832)>, u'emptyFolder/', ''): True
  (D)s4cmd.py:136  << s3walk(<ThreadUtil(Thread-2, started daemon 139988065752832)>, <__main__.S3URL instance at 0x7f5183859248>, u'emptyFolder/', '', []): None
  (D)s4cmd.py:136  << s3walk(<__main__.S3Handler object at 0x7f5183f6f910>, 's3://kinx-log/'): [{'is_dir': False, 'last_modified': datetime.datetime(2018, 7, 18, 2, 31, 55, tzinfo=tzutc()), 'name': u's3://kinx-log/emptyFolder/', 'size': 0}]
  (D)s4cmd.py:136  << relative_dir_walk(<__main__.S3Handler object at 0x7f5183f6f910>, 's3://kinx-log/'): [u'emptyFolder']
  (D)s4cmd.py:134  >> download(<ThreadUtil(Thread-3, started daemon 139988065752832)>, u's3://kinx-log/emptyFolder', u'/usr/local/globalcdn/s3_test/emptyFolder')
  (D)s4cmd.py:134  >> lookup(<ThreadUtil(Thread-3, started daemon 139988065752832)>, <__main__.S3URL instance at 0x7f51837adcf8>)
  (D)s4cmd.py:404  >> S3APICALL head_object(Bucket=u'kinx-log', Key=u'emptyFolder')
  (D)s4cmd.py:136  << lookup(<ThreadUtil(Thread-3, started daemon 139988065752832)>, <__main__.S3URL instance at 0x7f51837adcf8>): None
  (E)s4cmd.py:188  [Runtime Failure] The obj "emptyFolder" does not exists.
  (E)s4cmd.py:188  [Thread Failure] The obj "emptyFolder" does not exists.

**Comment by navinpai** [comment]
Hey,
How did you install s4cmd? I have a feeling this is related to the zero-file size issue which was fixed recently (but is pending release).

Can you list out the commands you used which are failing?

**Comment by dogenius01** [comment]
Hi,

I installed s4cmd in this way => $ pip install s4cmd.

Failed command list
$ s4cmd dsync s3://xxx/some/path/dir1/ /data/s4cmd_test/dir1/

**Comment by navinpai** [comment]
Yes, this looks to be the same issue which was fixed in #66. Tests have also been updated to test for this case. For a fix, you can either wait for a release, which should happen soon and then update through pip itself or simply make the required change in s4cmd.py on your local machine (The fix is just 2-3 lines: https://github.com/bloomreach/s4cmd/pull/81/files).

Closing this issue as fixed, since the fix is in master and pending release.

**Comment by dogenius01** [comment]
Great, thank you for the feedback.
