### ISSUE TITLE
Update debian release for s4cmd 2.1.0

### ISSUE THREAD

**Issue by navinpai** [bloomreach/s4cmd#132]
We need to make an updated release for s4cmd 2.1.0 on debian to allow apt-get update to get the new version.

Unsure what process was followed last time, and what the process entails

FYI @rozuur

**Comment by adeptg** [comment]
https://packages.debian.org/search?keywords=s4cmd&searchon=names&suite=all&section=all

buster (testing) (utils): Super Amazon S3 command line tool
2.1.0+ds-1: all 

Looks like it's already done

**Comment by navinpai** [comment]
Yup, looks like it was already picked up. Thanks to the debian maintainer Sascha Steinbiss.

Closing this issue.

Thanks for the heads up @adeptg
