### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by timtimellis** [bloomreach/s4cmd#14]
Seems to not like unicode - example from sync below:

s3://skrivapa-staging/1491993470/Testavtal.pdf.pdf => /local/1491993470/Testavtal.pdf.pdf
'ascii' codec can't encode character u'\xe5' in position 35: ordinal not in range(128)

**Comment by chouhanyang** [comment]
Are you using non-ASCII in your s3 path? Not seeing it in your example: "s3://skrivapa-staging/1491993470/Testavtal.pdf.pdf" here.

**Comment by bendenoz** [comment]
I am experiencing the same problem, and replacing all instances of the following appears to fix it, although I have not made extensive testing

```diff
-      key = bucket.get_key(s3url.path)
+      key = bucket.get_key(s3url.path.decode('utf-8'))
```

**Comment by navinpai** [comment]
Closing this as dupe of #74
