### ISSUE TITLE
--server-side-encryption

### ISSUE THREAD

**Issue by ewah** [bloomreach/s4cmd#17]
can we get a server side encryption option for the various commands.

**Comment by chouhanyang** [comment]
I think it is a bit too much for a simple tool to have encryption, maybe this can be added as plugins.
Which type of encryption you have in mind?

**Comment by rouge8** [comment]
S3 provides server side encryption, all you need is the `encrypt_key` parameter to a boto request.

**Comment by chouhanyang** [comment]
Implemented in s4cmd 2.0 with boto3. Please check out the new version. Thanks!
