### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by nitrocode** [bloomreach/s4cmd#175]
It would be nice to have homebrew support like s3cmd

https://github.com/Homebrew/homebrew-core/blob/master/Formula/s3cmd.rb

**Comment by chenrui333** [comment]
I dont think it is useful for a repo that is not actively maintained and released.

**Comment by nitrocode** [comment]
We can always create a custom tap, no?

**Comment by debodirno** [comment]
Go ahead, raise a pull request in homebrew-core and link it here.

**Comment by chenrui333** [comment]
@nitrocode @debodirno I see there are some new commits in this repo this year, so I went ahead filing a PR of introducing this new tool into homebrew-core registry.

I also proposed to add dependabot to track down the dependency changes to keep the project stay healthy 
- #194

**Comment by chenrui333** [comment]
Now you should be able to install with `brew install s4cmd`.

**Comment by debodirno** [comment]
Thank you @chenrui333!  I have merged your PR.
