### ISSUE TITLE
What about excluding directories?

### ISSUE THREAD

**Issue by illectronic** [bloomreach/s4cmd#31]
We have directories such as .svn which we don't want uploaded. Would you consider adding include/exclude?

Thanks.

**Comment by ixodie** [comment]
We'd love to try this but we need --exclude-from like in s3cmd.

Thanks!

**Comment by illectronic** [comment]
I am already trying to custom code it but I am running into a lot of issues on the s3walk side.

**Comment by ixodie** [comment]
Yeah, this is a must have feature.

**Comment by chouhanyang** [comment]
It is kind of tricky because comparing two directory path with the possibility of trailing slashes, relative/absolution paths whiling recursive walk into the directory. Maybe you can try to catch this after s3walk first (while sorting the final output) and then gradually improving the efficiency?

**Comment by dannyman** [comment]
+1

**Comment by navinpai** [comment]
Closing this as a dupe of #88 (as that's to support a superset exclude and include dir feature so it's easier to track in one issue).
