### ISSUE TITLE
escape % in s3 path

### ISSUE THREAD

**Issue by kkc** [bloomreach/s4cmd#33]
I find out a error while S3 path includes %. 
```
text = (msg % args) 
```
above source code shows `TypeError: not enough arguments for format string`
I would suggest s4cmd could use [advance string format](https://www.python.org/dev/peps/pep-3101/) to avoid this problem.

Thanks.

**Comment by chouhanyang** [comment]
No, that is is a bug in a call site when we call message(str) instead of message('%s', str). Kind of old school. This is no longer an issue in new versions. I can get/put/list files with % symbols.

Can you test with newer versions? Thanks.
