### ISSUE TITLE
s4cmd does not recognise square brackets and french character in the path

### ISSUE THREAD

**Issue by d33pika** [bloomreach/s4cmd#4]
If the path is "[mix]abc.txt" s4cmd returns [Runtime Failure] Source doesn't exist.

**Comment by navinpai** [comment]
The issue is invalid. 

`$ touch [as]sd.txt
$ s4cmd put [as]sd.txt s3://br-tmp/npai/
[as]sd.txt => s3://br-tmp/npai/case9-2/[as]sd.txt
`

**Comment by JohnnyBoi888** [comment]
I think this one is actually still an issue? Please see below for reproducing the issue with square brackets in pathing:

# pip freeze | grep s4cmd
s4cmd==2.1.0

# find /tmp/storage/
/tmp/storage/
/tmp/storage/storage_[default]_123
/tmp/storage/storage_[default]_123/jltest
/tmp/storage/storage_default_123
/tmp/storage/storage_default_123/jltest2

# aws s3 ls s3://jl-tmp/

# s4cmd sync -r /tmp/storage/ s3://jl-tmp/
/tmp/storage/storage_default_123/jltest2 => s3://jl-tmp/storage/storage_default_123/jltest2
/tmp/storage/storage_[default]_123/jltest => s3://jl-tmp/storage/storage_[default]_123/jltest

# s4cmd ls -r s3://jl-tmp/
2019-08-01 19:28 0 s3://jl-tmp/storage/storage_[default]_123/jltest
2019-08-01 19:28 0 s3://jl-tmp/storage/storage_default_123/jltest2

# s4cmd ls -r s3://jl-tmp/storage/storage_default_123/
2019-08-01 19:28 0 s3://jl-tmp/storage/storage_default_123/jltest2

# s4cmd ls -r s3://jl-tmp/storage/storage_[default]_123/

# s4cmd ls -r s3://jl-tmp/storage/storage_\[default\]_123/

#
