### ISSUE TITLE
recursive put includes the parent directory

### ISSUE THREAD

**Issue by jedierikb** [bloomreach/s4cmd#47]
moving to s4cmd from s3cmd, found a difference in how recursive put is handled

```
s4cmd -r -f /home/ec2-user/da-stuff/ s3://da-bucket/uploads/
```

will successfully put the files, but it includes the parent directory too ('da-stuff' in this example).

```
/home/ec2-user/da-stuff/6.pdf => s3://da-bucket/uploads/da-stuff/6.pdf
```

when I was expecting

```
/home/ec2-user/da-stuff/6.pdf => s3://da-bucket/uploads/6.pdf
```

What is the right way to get this behavior?

**Comment by chouhanyang** [comment]
Correct. s4cmd is more close to UNIX cp command. cp -r /home/ec2-user/da-stuff/ /some-dir/ actually move da-stuff into some-dir/.

To achieve what you want, you can add * for expansion, like:

s4cmd -r -f /home/ec2-user/da-stuff/* s3://da-bucket/uploads/

which is the reason why we move away from s3cmd and reimplement this in s4cmd. See the compatibility section for more information.
