### ISSUE TITLE
--multipart-split-size claims to be in MB, but is actually in bytes

### ISSUE THREAD

**Issue by njsmith** [bloomreach/s4cmd#53]
`s4cmd --help` says:
```
  --multipart-split-size=MULTIPART_SPLIT_SIZE
                        size in MB to split multipart transfers
```

I wanted to use a larger-than-normal split size while uploading a very large file, so I tried using `--multipart-split-size=1000`. `s4cmd` responded by eating up tens of gigabytes of memory and had to killed.

It turns out that contrary to what `--help` says, in the current implementation the units for `--multipart-split-size` are bytes, not MB. So `s4cmd` crashed because it tried to allocate python objects to describe tens of millions of splits.

Either the docs should be fixed, or the code should be changed so that this is actually measured in MB (probably the latter is better).

**Comment by chouhanyang** [comment]
Fixed. Thank you.
