### ISSUE TITLE
Allow setting access key & secret key from command line, like s3cmd

### ISSUE THREAD

**Issue by awbacker** [bloomreach/s4cmd#55]
s3cmd has the option to set these variables from the command line, which I think is very useful and sadly seems to be missing from s4cmd.

I connect to different hosts for s3 (eu, us, china), and/or with different credentials or in subshells spawned by the build server.  Not having the ability to set this on the command line means I can't use s4cmd at all, though it seems worth a try.

**Comment by chouhanyang** [comment]
You can use environment variables before a command in bash?

S3_ACCESS_KEY_NAME=xxx S3_SECRET_KEY_NAME=yyy s4cmd ...

for example?

**Comment by chouhanyang** [comment]
--access-key and --secret-key just added in 2.0.1. Let me know. Thanks.
