### ISSUE TITLE
"specified endpoint" error

### ISSUE THREAD

**Issue by wytcld** [bloomreach/s4cmd#60]
[Exception] An error occurred (PermanentRedirect) when calling the ListObjects operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
[Thread Failure] An error occurred (PermanentRedirect) when calling the ListObjects operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

With 2.0. This is attempting to do an ls, where s3cmd works.

**Comment by wytcld** [comment]
Turns out that, like awscli, this requires an environment variable set, such as:

export AWS_DEFAULT_REGION=us-west-2

Is this documented somewhere I've missed?

**Comment by chouhanyang** [comment]
I think the default may be us-east-1 if no configuration. That's part of boto3 configuration: http://boto3.readthedocs.io/en/latest/guide/quickstart.html#using-boto-3

**Comment by navinpai** [comment]
Since this is resolved, I'm closing the issue.
