### ISSUE TITLE
Files with size 0kb fail to upload also breaking the complete upload process

### ISSUE THREAD

**Issue by pawan-darda** [bloomreach/s4cmd#66]
Command being used --- 
python s4cmd.py \
dsync local-folder/ s3://path/ \
--access-key=xyz\
--secret-key=xyz\
--API-ACL='public-read' \
--recursive --force \
--ignore-empty-source \
--multipart-split-size=51200 \
--retry=5 --retry-delay=1 \
--num-threads=10

**Comment by benjaminrigaud** [comment]
I have a similar issue.
When uploading (put recursive) a directory containing some empty files: some threads fails and the put is incomplete (many non empty files not uploaded too).

**Comment by keithslater** [comment]
Same issue here. Also have the problem if a file is deleted after the command runs but before it tries to transfer it. Completely stops the s4cmd command and have to start over. Makes it pretty much impossible to transfer several hundred GB working directories.

**Comment by dannyman** [comment]
I have a proposed fix in Issue #78

**Comment by navinpai** [comment]
The fix was merged into master. Thanks for the bug report!
