### ISSUE TITLE
IAM authentication within s4cmd

### ISSUE THREAD

**Issue by chaosblog** [bloomreach/s4cmd#71]
Is there a way to use IAM-roles for authentication in the s4cmd version 2.0?
When using "pure" boto3 I can use IAM without any complications.

**Comment by xelfer** [comment]
agreed, this would be a very useful feature.

**Comment by iceboundflame** [comment]
+1: any way for s4cmd to omit credentials and fall back to IAM authentication, as boto does automatically?

**Comment by lexmag** [comment]
I assume this issue can be closed since #96 was merged. :bowtie:

**Comment by navinpai** [comment]
Since I hear no complaints, going ahead and closing this issue! :+1:
