### ISSUE TITLE
An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

### ISSUE THREAD

**Issue by komalsrathi** [bloomreach/s4cmd#75]
I am trying to sync two buckets, both of which I have access to:

```
# created destination bucket to store data
$ s3cmd ls s3://toil.20k
                       DIR   s3://toil.20k/gtex/
                       DIR   s3://toil.20k/pnoc/
                       DIR   s3://toil.20k/target/
                       DIR   s3://toil.20k/tcga/
					   
# publicly accesible source bucket I am trying to get data from
# without --requester-pays I cannot even ls on this bucket
$ s3cmd --requester-pays ls s3://cgl-rnaseq-recompute-fixed/gtex
                       DIR   s3://cgl-rnaseq-recompute-fixed/gtex/
2016-06-03 17:02    435553   s3://cgl-rnaseq-recompute-fixed/gtex-manifest
```

I had two approaches:

1. Get-Put
```
# get from source bucket to an EBS volume
s3cmd get s3://cgl-rnaseq-recompute-fixed/gtex/$i ./
# put into destination bucket
s3cmd put ./$i s3://toil.20k/gtex/ 
# remove from EBS
rm ./$i 
```
I have this working in the background but I wanted to test the second approach where you can just copy/sync between buckets without having to store them temporarily on an EBS volume.

2. Sync between buckets
I read that s4cmd is faster than s3cmd but when I use this:

```
$ s4cmd --dry-run sync s3://cgl-rnaseq-recompute-fixed/gtex s3://rnaseq.toil.20k/gtex

# I get the following error
[Exception] An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
[Thread Failure] An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

Like I said I cannot `ls` on the source bucket without `--requester-pays`. Would that be causing the error? I see there is no `--requester-pays` argument for `s4cmd`. How can I use s4cmd to sync two buckets?

Thanks!

**Comment by xelfer** [comment]
I'm also getting this error.. and I swear it worked about a month ago when I was using it previously. 

I'm also getting this error when trying to dsync: 
`[Exception] An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
`
when an ls works fine:
`$ s4cmd ls s3://cms-files/
                    DIR s3://cms-files/uploads/
2016-05-06 04:53  85351 s3://cms-files/01.pdf
2016-05-06 04:53 663665 s3://cms-files/06.pdf
2016-06-20 04:16 171308 s3://cms-files/17.pdf
`
