### ISSUE TITLE
Files that equal 0 bytes break this program

### ISSUE THREAD

**Issue by lanmalkieri** [bloomreach/s4cmd#78]
/cassandra_backups/data/cassandra/data/clearcore/transactions/clearcore-transactions-jb-15105-Summary.db => s3://cassandra-backups.us-east[Runtime Failure] Unable to read data from source: /cassandra_backups/data/cassandra/data/clearcore/transactions/clearcore-transactions-jb-17476-Statistics.db
[Runtime Failure] Unable to read data from source: /cassandra_backups/data/cassandra/data/clearcore/transactions/clearcore-transactions-jb-17476-Data.db
[Runtime Failure] Unable to read data from source: /cassandra_backups/data/cassandra/data/clearcore/transactions/clearcore-transactions-jb-17476-CompressionInfo.db
[Runtime Failure] Unable to read data from source: /cassandra_backups/data/cassandra/data/clearcore/transactions/clearcore-transactions-jb-17476-Index.db
[Runtime Failure] Unable to read data from source: /cassandra_backups/data/cassandra/data/clearcore/transactions/clearcore-transactions-jb-17476-Filter.db

The thing all of these files share is that they all (for whatever reason) were 0 bytes. After testing on a single 0 file created by dd sure enough this breaks the program. 

Specific flags I am using

s4cmd dsync --verbose --recursive --delete-removed -c 7 $dir_src/ "$s3_url/$dir_target/"

I will look in the code tomorrow to see if anything pops out that I can help on in looking at this issue.

**Comment by lanmalkieri** [comment]
I'm assuming without looking that this may be relevant to some size operator that determines local file size before pushing to S3 to determine if the file needs to be chunked or not. 

Maybe a divide by zero sort of thing?

haha.

**Comment by dannyman** [comment]
Me too. I assume there's a test "can I read the file" that evaluates as a string .. if the string is empty, then you can not read the file ...

**Comment by dannyman** [comment]
Yeah here we go:
```
  @log_calls
  def read_file_chunk(self, source, pos, chunk):
    '''Read local file cunks'''
    data = None
    with open(source, 'rb') as f:
      f.seek(pos)
      data = f.read(chunk)
    if not data:
      raise Failure('Unable to read data from source: %s' % source)
    return StringIO(data)
```
See: https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> if '':
...  print "true"
... 
>>> 
```
We need something other than `if not data` ... I think you really just to "try .. open .. except" ...

**Comment by dannyman** [comment]
This appears to work:
```
  @log_calls
  def read_file_chunk(self, source, pos, chunk):
    '''Read local file cunks'''
    data = None
    with open(source, 'rb') as f:
      f.seek(pos)
      data = f.read(chunk)
    if not f:
      raise Failure('Unable to read data from source: %s' % source)
    return StringIO(data)
```

**Comment by rd350** [comment]
This code does'nt seem to work for me.
`s4cmd dsync -r -t 1000 --ignore-empty-source --num-threads=4 forms/ s3://bucket/GJ/OM/`

Error:
[Thread Failure] Unable to read data from source: /home/ubuntu/path to file

**Comment by rd350** [comment]
Never mind, it worked. I had to call the s4cmd.py file

**Comment by sfarrell5123** [comment]
this worked for me also, please commit this change

**Comment by navinpai** [comment]
Duple of #66 .
